name: Print Directory Structure Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: workflow_dispatch
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: XDTesting Print Directory Structure
        uses: FiorelaCiroku/XDTesting-Print-Directory-Structure@v1.0.2
  
